import React from 'react'
import './globals.css'
import { Roboto } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'

const inter = Roboto({
  subsets: ['latin'],
  weight: '500',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
